Destek\Entity\Priority:
    type: entity
    table: priority
    repositoryClass: Destek\Entity\Repository\PriorityRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            nullable: true
            length: 30
        deleted:
            type: boolean
            options:
                default: false               
        deleted_at:
            type: datetime   
            nullable: true
        created_at:
            type: datetime   
        updated_at:
            type: datetime
            nullable: true
    lifecycleCallbacks: 
