Destek\Entity\TicketReplies:
    type: entity
    table: ticket_replies
    repositoryClass: Destek\Entity\Repository\TicketRepliesRepository
    indexes:
        ticket_id:
            columns: [ticket_id]
        reply_user_id:
            columns: [reply_user_id]
        deleted:
            columns: [deleted]
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        ticket_id:
            type: integer
            length: 11
        reply_user_id:
            type: integer
            length: 11
        message:
            type: text
            nullable: true
        ip:
            type: string
            length: 50
            nullable: true
        created_at:
            type: datetime
            length: 20
            nullable: true
        updated_at:
            type: datetime
            length: 20
            nullable: true
        deleted:
            type: boolean
            nullable: true
        deleted_at:
            type: datetime
            length: 20
            nullable: true
    lifecycleCallbacks: {  }
