CREATE TABLE category (
id INT AUTO_INCREMENT NOT NULL,
user_id INT NOT NULL,
name INT NOT NULL,
status TINYINT(1) DEFAULT '0',
deleted TINYINT(1) DEFAULT '0' NOT NULL,
deleted_at DATETIME DEFAULT NULL,
created_at DATETIME NOT NULL,
updated_at DATETIME DEFAULT NULL,
PRIMARY KEY(id)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;




CREATE TABLE priority (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, name INT NOT NULL, deleted TINYINT(1) DEFAULT '0' NOT NULL, deleted_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE ticket_category (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, category_id INT NOT NULL, ticket_id INT NOT NULL, deleted TINYINT(1) DEFAULT '0' NOT NULL, deleted_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
