<?php

namespace Destek\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{

    /**
     * @param $id
     * @param $name Kategori adı
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function recordCategory($id, $name)
    {
        $qb = $this->createQueryBuilder('c');
        $qb->where('c.id <> :id')
            ->andWhere('c.name = :name')
            ->andWhere('c.deleted =:deleted')
            ->setParameters(array(
                'id' => $id,
                'name' => $name,
                'deleted' => false
            ));
        return $qb->getQuery()->getOneOrNullResult();
    }

    /**
     * @return array
     */
    public function getCategory()
    {
        $qb = $this->createQueryBuilder('c')
            ->select('c.id', 'c.name')
            ->where('c.deleted = false');

        $categoryLists = $qb->getQuery()->getArrayResult();
        $record = array();

        foreach ($categoryLists as $categoryList) {
            $record[$categoryList['id']] = $categoryList['name'];
        }

        return $record;
    }

}
