<?php

namespace Destek\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PriorityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PriorityRepository extends EntityRepository
{

    public function getPriority()
    {
        $qb = $this->createQueryBuilder('p')
                   ->select('p.id', 'p.name')
                   ->where('p.deleted = false');

        $priorityLists = $qb->getQuery()->getArrayResult();
        $record = array();

        foreach ($priorityLists as $priorityList) {
            $record[$priorityList['id']] = $priorityList['name'];
        }

        return $record;
    }
}
