<?php

namespace Destek\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TicketStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketStatusRepository extends EntityRepository
{
}
