<?php

namespace Destek\Entity\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * TicketsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class TicketsRepository extends EntityRepository
{
    /**
     * @param null $ownerUserId
     * @param null $recepientId
     * @param null $id
     * @return array|mixed
     */
    public function getTicketList($ownerUserId = null, $recepientId = null, $id = null)
    {
        $qb = $this->createQueryBuilder('t')
            ->select('t');


        if ($recepientId !== null) {

                if ($id !== null) {
                $qb->where('t.recipient_id = :recepientId AND t.deleted = 0 AND t.id = :id')
                    ->setParameters(array(
                    'recepientId' => $recepientId,
                    'id' => $id
                    ));
            } else {
                $qb->where('t.recipient_id = :recepientId AND t.deleted = 0')
                    ->setParameters(array(
                    'recepientId' => $recepientId
                ));
            }
        } else {
            if ($id !== null) {
                $qb->where('t.owner_user_id = :ownerUserId AND t.deleted = 0 AND t.id = :id')
                    ->setParameters(array(
                    'ownerUserId' => $ownerUserId,
                    'id' => $id
                    ));
            } else {
                $qb->where('t.owner_user_id = :ownerUserId AND t.deleted = 0')->setParameters(array(
                    'ownerUserId' => $ownerUserId
                ));
            }
        }

        if ($id !== null) {
            return $qb->getQuery()->getOneOrNullResult();
        } else {
            return $qb->getQuery()->getArrayResult();
        }
    }
}
