<?php

namespace Destek\Entity\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * TicketRepliesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepliesRepository extends EntityRepository
{
}
